import HeaderNav from "@/components/HeaderNav";
import "../assets/css/style.css";
export const metadata = {
  title: 'Bijoy 2024',
  description: 'Generated by Bijoy 2024',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
      </head>
      <body>
        <HeaderNav />
        {children}

      </body>
    </html>
  )
}


